php練習問題2
DaisukeKikukawa/codegym-php pull request #2
Opened 2021-04-27 12:02 UTC by DaisukeKikukawa

確認のほど宜しくお願いいたします。

2021-04-27 12:11 UTC, kai-kou commented
不要なスペースがありますので、取り除いてください。
https://github.com/DaisukeKikukawa/codegym-php/blob/5236f7ab3a4a564918ba21177de74e12d82c8e2c/html/php-pre-challenge2/index.php#L6

こういった不要なスペース、改行をなどを強調表示してくれるVSCodeの拡張機能があるので、調べて導入してみてください。
<img width="409" alt="スクリーンショット 2021-04-27 21 08 54" src="https://user-images.githubusercontent.com/41495183/116238952-075a6200-a79d-11eb-970d-ff7e5dd97119.png">

2021-04-27 12:30 UTC, kai-kou commented
【修正不要】
コミットメッセージについて

>練習問題2番になります。 
>確認のほど宜しくお願いいたします。

とありますが、これはプルリクエストする際のメッセージになっており、コミットメッセージとしてはふさわしくありません。
コミットメッセージはどういった変更を加えたのかを説明するものなので、ご自身のHTML課題にあるコミット `ulタグのインテンドの位置を揃えました。` のようにコミット内容がわかるメッセージをするよう心がけてください。

https://github.com/DaisukeKikukawa/codegym-html/commit/0a517b2c0863d46feccb23bab46443e2dfe22406

2021-04-28 10:13 UTC, TomoakiTANAKA commented
> print_rをした際に、次の形式で出力されること

- [notion](https://www.notion.so/2-ac5a0a36b9db461ab279a48541ef7d4e)

今回の課題では、結果を確認するため、出力する部分までロジックの記述をお願いします。（ソート自体は良さそうです）。

2021-04-28 10:19 UTC, TomoakiTANAKA commented on html/php-pre-challenge2/index.php
> +  for ($n = 1; $n < count($array); $n++) {
修正不要

ループの変数ですが、慣習でこんな感じになっています。参考まで。

- iを使う場合：i -> j -> k の順に使う（これが一番使います。i = indexの略ですね。）
- a を使う場合：a -> b -> c の順（書いたものの、あまり使いません）
- x を使う場合：x -> y -> z の順（図形や画像の処理のときは、x軸y軸のような座標を意識してループ処理をすることがあるのでこういったのを使います）

なお「n」は総数を意味するので、ループのカウンタにはあまりつかいません。

2021-04-28 10:19 UTC, TomoakiTANAKA commented on html/php-pre-challenge2/index.php
> +  for ($n = 1; $n < count($array); $n++) {
要修正

ループ内で常に返り値が変わらないメソッド（今回でいうと`count($array)`）を使うのをやめましょう。
理由は、ループの条件判定のたびに処理を呼び出して無駄なことをしているからです。

ループの最大値などは、ループ処理とは別に取得しておき、ループないでは値を参照するだけにするのが基本です。

例えば下記のコードを動かすと、my_countがたくさん動いてるのが実感できると思います。

```php
// 受け取ったarrayのcountするだけの関数
function my_count($array) {
  print_r('call my_count');
  return count($array);  
}

// 修正はここから
for ($i = 0; $i < my_count($array); $i++) {
  for ($n = 1; $n < my_count($array); $n++) {
    if ($array[$n - 1] > $array[$n]) {
      $temp = $array[$n];
      $array[$n] = $array[$n - 1];
      $array[$n - 1] = $temp;
    }
  }
}
```

2021-04-28 11:31 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +$array_number = count($array);
```suggestion
$array_length = count($array);
```

2021-04-28 11:34 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +  for ($j = 1; $j < $array_number; $j++) {
```suggestion
for ($i = 0; $i < $array_number - 1; $i++) {
  for ($j = 1; $j < $array_number - $i; $j++) {
```

2021-04-28 11:38 UTC, Yuzunoha requested changes
出力結果はOKです！
性能とコード品質に関するコメントをしたのでご確認ください。

2021-04-28 12:16 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +  for ($j = 1; $j < $array_length-$i; $j++) {
```suggestion
for ($i = 0; $i < $array_length - 1; $i++) {
  for ($j = 1; $j < $array_length - $i; $j++) {
```
(修正不要)
要修正とまでは言いませんが、他の行にスタイルを合わせて演算子の左右に半角スペースを入れた方がよいです。エディタの自動整形機能を使いましょう。

2021-04-28 12:17 UTC, Yuzunoha commented on html/php-pre-challenge2/index.php
> +  for ($j = 1; $j < $array_length-$i; $j++) {
というか理由がない限り提案されたコードをコピペしたほうがよいです。

2021-04-28 12:19 UTC, Yuzunoha approved these changes
LGTMです！！！
修正不要のコメントをしているのでご確認ください(このブランチにはこれ以上コミットせずにマージしてください)。

2021-04-28 12:23 UTC, merged