リツイート機能の実装
DaisukeKikukawa/codegym-php pull request #3
Opened 2021-05-14 09:38 UTC by DaisukeKikukawa

2021-05-15 06:52 UTC, disneyLadySango reviewed
@DaisukeKikukawa 
お疲れさまです、レビュー実施しました！
何点かコメント入れましたのでご確認ください！

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +
[should]
すごい空白開いてしまっているので修正お願いします

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +
[should]
こちらもすごい空白ありますね

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +    $is_retweet_post_id = null;
[must]
`isXXX`や`hasXXX`といった変数名は基本booleanの場合に使う名称なので、
他の名称にしていただければと思います

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                    ?>
[must]
こちらで用意している
$retweet_recordと$rt_postはどうやら使っていないようなので削除しても良いとおもいますが
どこかで使用していますでしょうか？

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
[Q]
goodCheckの関数はbooleanで返却していないような気がするのですが、
ここのif文としてはどういった条件の時にtrueになるのでしょうか？

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                        } elseif (myRetweetCounts($post) !== '0') {
[should]
こちらの関数についてですが、
現在は「自分のリツイートした件数を取得する処理」となっています

が、実際にやりたいことは「自分がリツイートしたかどうか」がわかれば良いのではないでしょうか？

そのため、
```
    return $all_post['cnt'];
を
   return $all_post['cnt'] !== '0'
```
とし、`true` `false`で返却する方が関数の使い方としては適切ではないでしょうか？

また上記の変更を行った場合`isRetweetMyself`といった関数名にしてあげるとわかりやすくなると思います

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                        <a href="index.php?quit-retweet=<?php echo htmlspecialchars($post['id'], ENT_QUOTES); ?>"><img class="retweet-image" src="images/retweet-solid-blue.svg"></a>
[must]
この場合の条件は
`myRetweetCounts`でも同じ結果が出ると思いますがいかがでしょうか？
そうなるとここの条件は消すことができ、`myRetweetCounts($post) !== '0'`かどうかのみで表示の分岐が可能になります

2021-05-15 06:52 UTC, disneyLadySango commented on html/php-challenge/index.php
> +function goodCheck($post)
[must]
ここ改めて課題に画像イメージがあるのでみてみてください。
現在のいいねは
「いいねしたIDのツイートにいいねがつく」
となっていますが、ここはRTと同じような考え方にして欲しいので、
「リツイートしたツイートをいいねしたら元ツイートにいいねがつく」
「元ツイートにいいねしたらそのまま元ツイートにいいねがつく」
というのを実現してください。

要はRT機能と考え方は全く同じです

2021-05-15 11:10 UTC, DaisukeKikukawa commented on html/php-challenge/index.php
> +                    ?>
削除し忘れていたので修正させて頂きました🙇🏼‍♂️

2021-05-17 11:54 UTC, Yuzunoha commented on html/php-challenge/index.php
> +                                        <a href="index.php?quit-retweet=<?php echo htmlspecialchars($post['id'], ENT_QUOTES); ?>"><img class="retweet-image" src="images/retweet-solid-blue.svg"></a>
せっかく `function h` というhtmlspecialchars のラッパー関数を用意しているので、htmlspecialchars を直接使わずhを使うようにしましょう！

ラッパー関数を使ったり使わなかったりするというのはバグの温床とされます。

htmlspecialcharsで検索かけてソース全体を確認しましょう♪

2021-05-17 12:08 UTC, Yuzunoha commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
@DaisukeKikukawa 
再レビュー前にレビュアからもらった質問にgithub上で返信しましょう～

2021-05-17 12:20 UTC, DaisukeKikukawa commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
こちら関数の方を修正しました🙇🏼‍♂️

2021-05-17 12:25 UTC, Yuzunoha commented on html/php-challenge/index.php
> +</html>
![image](https://user-images.githubusercontent.com/22877094/118486203-4c4a3680-b754-11eb-96cf-07fa21bf76f3.png)

githubで警告が出るので、最終行の末尾で1回改行しましょう！
VSCodeで insert final newline というオプションをonにすれば保存時に自動でやってくれます。

2021-05-17 13:14 UTC, Yuzunoha commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
@DaisukeKikukawa
コミュニケーションがすごく大切なので、厳しいようですがコメントします！

>関数の方を修正しました🙇🏼‍♂️

短くてよいのでどのように修正したのか明記してください。

>ここのif文としてはどういった条件の時にtrueになるのでしょうか？

と質問されているので、回答を明記してください。

2021-05-17 13:29 UTC, Yuzunoha commented
![image](https://user-images.githubusercontent.com/22877094/118496231-e616e100-b75e-11eb-97af-1d3c591b4ee5.png)

リツイートを実行してから画面更新するとリツイートを再度実行してしまいます。画面更新するだけでリツイートしてしまう動作を改善してください。

そもそも同じユーザは同一の投稿に対して1回までしかリツイートできない(一人が同じ投稿を何度もリツイートできない)仕様なので、一人で何度もリツイートできてしまう動作を改善してください。

2021-05-17 13:29 UTC, Yuzunoha requested changes
コメントしたので一旦お返しします。

2021-05-22 04:46 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
@DaisukeKikukawa 
こちらいかがでしょうか？

関数や処理に問題ないかというより、
「どういう時にTrueとなり、どういう時にFalseになるか？」
という点を菊川さんがきちんと理解できているかどうかをお聞きしたく質問したのが経緯です！

なので単純に「こういう値がくるとTrueになり、こういう値がくるとFalseになります」と言った旨の返信をいただければ幸いです！

2021-05-22 05:27 UTC, disneyLadySango reviewed
@DaisukeKikukawa 
実装面で何点かコメントしました。
個人的には見れば分かるという部分もあるのですが、菊川さんが自身の書いたコードを理解しているか？という意味も込めて質問コメントも出しましたので、こちらご回答をお願いします！

これは完全に普段のレビューの癖で書いてしまっているのですが、
- must -> 必須対応
- should -> 対応すべき
- nits -> 軽微な修正
- imo -> 自分だったらこうするけどどうでしょうか
- Q -> 質問
- Good -> とても良い！素晴らしい
などでレビューのコメントをラベリングしております。
Qについては質問コメントなので、こちらは必須で返信をお願いします。
また軽微な指摘コメントについては無理に返信しなくてもOKです。
よく実務でやるのは対応したものに順次スタンプをつけていったりするなどはするのでそのようにしていただいても構いません！

他の講師からはラベリングされたコメントはあまりこないと思いますが、
質問に準ずるコメントがきたら返信するようにしましょう！

また画面を触っていた時に不審な動きをしていたので、
以下の実装について確認お願いします！

Aさん
Bさん
Cさん
の3人がいる時

Aさん　おはようございます
というツイートをBさんがRT
そのBさんのRTしたツイートのうちCさんがRTを行うと以下のような結果となりました

・Aさんの元ツイートをRTすると元ツイート、BさんのRT、CさんのRTが全てRT状態となり件数が2となる
・BさんのRTしたツイートをRTすると、BさんのRT、CさんのRTのみがRT状態となり件数が1となる

こちら動作としては
・BさんのRTしたツイートをRTしても、Aさんの元ツイートをRTした時と全く同じ動作となる
のが正しいです。修正お願いします！

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +    if ($quit_post['retweet_post_id'] !== '0') {
[must]
別のところでコメントしたところですが、そういう意味で行くとこちらは === ではなく !==という点でも実装がぶれていますね

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +function retweetedPost($post)
[Q]
この関数名で検索してみたんですがヒットしません
使用されてますでしょうか？
未使用でしたら削除しましょう！

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +function isRetweetMyself($post)
[Q]
こちらの関数も同様に使っていないようです
不要な削除しましょう！

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                        } elseif (myRetweetCounts($post)) {
[Q]
L289とL298の条件式の違いについて質問させてください。

`if (myRetweetCounts($post) !== '0') `
`if (myRetweetCounts($post))`

前者は関数名から察するに
「自分がリツイートをした件数が0ではなかったら＝自分がリツイートしていたら」
ということだと思ったのですが、
後者はどのような意味になるのでしょうか？

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                    <?php if (goodCheck($post)) : ?>
[must]
https://github.com/DaisukeKikukawa/codegym-php/pull/3#discussion_r637353646
上記のPRコメントで再度質問出させてもらってますのでご確認おねがいします

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                            <?php endif; ?>
[must]
ここインデントおかしいですね。
ここのインデントがずれているので、下もだんだんインデントが深くなってしまいます
L275 - L278 - L282は同じラインに揃うのが正しいのでそれに合わせてください。
また、それに合わせてこれ以降のコードのも修正お願いします。

そしてこちらも条件式の比較は実装ブレがありますね

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                    if ($post['reply_post_id'] > 0) :
[must]
retweet_post_idではないですが同様に0と比較する方式なので実装は揃えておいたほうがよいでしょう

2021-05-22 05:27 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                                    ?>
[must]
こういうところも細かくインデント揃えていきましょう
インデント揃えないで可読性が低くなりバグを生むコストよりインデントを揃えるコストの方が低いです

L304だと</a>の改行の後に<?phpが始まっていますが、ここだとそのまま続いていたりと記述方法に統一感を持たせてください

2021-05-27 12:04 UTC, DaisukeKikukawa commented on html/php-challenge/index.php
> +                                        } elseif (myRetweetCounts($post)) {
こちら不要でしたので削除させて頂きました。
わかりづらく申し訳ありません🙇🏼‍♂️

2021-05-27 12:04 UTC, DaisukeKikukawa commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
申し訳ありませんこちら明確に答えられていませんでした🙇🏼‍♂️

真偽値falseとの比較で値を返すように修正いたしました。

2021-05-27 12:12 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                        } elseif (myRetweetCounts($post)) {
承知しました！
いえいえ！菊川さんが理解して書いているコードであれば基本問題ないです！

2021-05-27 12:15 UTC, disneyLadySango commented on html/php-challenge/index.php
> +                                <?php if (goodCheck($post)) : ?>
@DaisukeKikukawa 
大丈夫です！承知しました！
口頭でご説明いただいた内容がそのまま回答ですので念のため転記しておきますね！

```
fetch()の結果が失敗した場合はfalseとなるので、!== falseとすることでデータの有無をチェックしている
``

2021-05-27 12:27 UTC, disneyLadySango approved these changes
@DaisukeKikukawa 
レビュー実施しました！！！
LGTMです！お疲れ様でした！

今回の実装で学んだところは多々あったかと思うので是非復習したもらえればと思います！
特に暗黙的キャストの部分は、
「なんで使うと良くないのか」
というところが説明できるくらいには理解しておいてほしいところです

とはいえ、ひとまずお疲れ様でした！いい実装になったと思います！

2021-05-27 12:35 UTC, merged